"""Constants for SAISYS SSB handling."""

from __future__ import annotations

XOR_KEY = 0xAA
CODE_FILE_NAME = "CODE.SSB"
DATA_FILE_NAME = "DATA.SSB"
JSON_FORMAT = "saisys-ssb-json"
JSON_VERSION = 1
CP932 = "cp932"
DEFAULT_TEXT_ENCODING = CP932
TEXT_ENCODING_ALIASES = {
    "win-31j": CP932,
    "windows-31j": CP932,
    "shift-jis": CP932,
    "shift_jis": CP932,
    "sjis": CP932,
    "ms932": CP932,
}

KNOWN_OPCODE_NAMES = {
    -0x80000000: "VM_DATA_LOAD_DWORD",
    -0x7FFFFFFF: "VM_DATA_STORE_DWORD",
    -0x7FFFFFFE: "VM_DATA_LOAD_BYTE",
    -0x7FFFFFFD: "VM_DATA_STORE_BYTE",
    -0x7FFFFFFC: "VM_DUP",
    -0x7FFFFFFB: "VM_DUP_SWAP",
    -0x7FFFFFFA: "VM_DROP",
    -0x7FFFFFF9: "VM_SET_PC_FROM_RET",
    -0x7FFFFFF8: "VM_SET_FLAG_3082",
    -0x7FFFFFF7: "VM_SET_FLAG_3086",
    -0x7FFFFFF6: "VM_JUMP_ABS",
    -0x7FFFFFF5: "VM_JUMP_REL",
    -0x7FFFFFF4: "VM_PUSH_PC_AND_JUMP_ABS",
    -0x7FFFFFF3: "VM_PUSH_PC_AND_JUMP_REL",
    -0x7FFFFFF2: "VM_JUMP_IF_TRUE_ABS",
    -0x7FFFFFF1: "VM_JUMP_IF_TRUE_REL",
    -0x7FFFFFF0: "VM_JUMP_IF_FALSE_ABS",
    -0x7FFFFFEF: "VM_JUMP_IF_FALSE_REL",
    -0x7FFFFFEE: "VM_DUP2",
    -0x7FFFFFED: "VM_SET_FLAG_3087",
    -0x7FFFFFEC: "VM_SKIP_RET_VALUES",
    -0x7FFF0000: "VM_ARITH_ADD",
    -0x7FFEFFFF: "VM_ARITH_SUB",
    -0x7FFEFFFE: "VM_ARITH_MUL",
    -0x7FFEFFFD: "VM_ARITH_DIV",
    -0x7FFEFFFC: "VM_ARITH_MOD",
    -0x7FFEFFFB: "VM_ARITH_OR",
    -0x7FFEFFFA: "VM_ARITH_AND",
    -0x7FFEFFF9: "VM_ARITH_XOR",
    -0x7FFEFFF8: "VM_ARITH_NOT",
    -0x7FFEFFF7: "VM_ARITH_NEG",
    -0x7FFEFFF6: "VM_CMP_EQ",
    -0x7FFEFFF5: "VM_CMP_NE",
    -0x7FFEFFF4: "VM_CMP_GE_ALT",
    -0x7FFEFFF3: "VM_CMP_LT",
    -0x7FFEFFF2: "VM_CMP_LE",
    -0x7FFEFFF1: "VM_MUL_DUP",
    -0x7FFEFFF0: "VM_DIV_DUP",
    -0x7FFEFFEF: "VM_MOD_DUP",
    -0x7FFEFFEE: "VM_CMP_GT",
    -0x7FFEFFED: "VM_CMP_GE",
    -0x7FFEFFEC: "VM_CMP_LT_ALT",
    -0x7FFEFFEB: "VM_CMP_LE_ALT",
    -0x7FFEFFEA: "VM_SHIFT_R_LOGICAL",
    -0x7FFEFFE9: "VM_SHIFT_L",
    -0x7FFEFFE8: "VM_SHIFT_R_ARITH",
    -0x7FFF0001: "VM_SET_WINDOW_TEXT",
    -0x7FFD0000: "VM_FORMAT_INT_OR_TEXT",
}
