#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import struct
from pathlib import Path

HEADER_STRUCT = struct.Struct("<4sIII16s")
ENTRY_STRUCT = struct.Struct("<16sII")
BLOCK_SIZE = 0x1000


def _from_b64(text: str) -> bytes:
    return base64.b64decode(text.encode("ascii"))


def pack_archive(manifest_path: Path, output_path: Path, update_checksum: bool) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    entries = list(manifest["entries"])
    file_count = len(entries)
    version_flags = int(manifest["version_flags"])

    table_size = ((24 * file_count + 31) & 0xFFFFF000) + 4064
    table_padding = _from_b64(manifest.get("table_padding_base64", ""))
    expected_padding_len = table_size - file_count * ENTRY_STRUCT.size
    if len(table_padding) != expected_padding_len:
        raise ValueError("manifest.table_padding_base64 length does not match file_count.")

    extra_region = _from_b64(manifest.get("extra_region_base64", ""))
    extra_size = len(extra_region)
    metadata_size = HEADER_STRUCT.size + table_size + extra_size
    if metadata_size % BLOCK_SIZE != 0:
        raise ValueError("Metadata region is not aligned to 4096 bytes.")

    table_blob = bytearray(file_count * ENTRY_STRUCT.size)
    file_blobs = []
    max_end_block = metadata_size // BLOCK_SIZE
    base_dir = manifest_path.parent

    for i, e in enumerate(entries):
        hash_bytes = bytes.fromhex(e["hash_hex"])
        start_block = int(e["start_block"])
        allocated_blocks = int(e["allocated_blocks"])
        file_rel = Path(e["file"])
        file_data = (base_dir / file_rel).read_bytes()
        padding = _from_b64(e.get("padding_base64", ""))
        allocated_bytes = allocated_blocks * BLOCK_SIZE
        payload = file_data + padding
        if len(payload) > allocated_bytes:
            raise ValueError(f"File exceeds allocated blocks: {file_rel.as_posix()}")
        if len(payload) < allocated_bytes:
            payload += b"\x00" * (allocated_bytes - len(payload))

        ENTRY_STRUCT.pack_into(table_blob, i * ENTRY_STRUCT.size, hash_bytes, start_block, len(file_data))
        file_blobs.append((start_block, payload))
        end_block = start_block + allocated_blocks
        if end_block > max_end_block:
            max_end_block = end_block

    archive = bytearray(max_end_block * BLOCK_SIZE)
    table_off = HEADER_STRUCT.size
    table_end = table_off + len(table_blob)
    table_region_end = table_off + table_size
    extra_off = table_region_end
    extra_end = extra_off + extra_size

    archive[table_off:table_end] = table_blob
    archive[table_end:table_region_end] = table_padding
    archive[extra_off:extra_end] = extra_region

    for start_block, payload in file_blobs:
        data_off = start_block * BLOCK_SIZE
        archive[data_off : data_off + len(payload)] = payload

    checksum = bytes.fromhex(manifest["checksum_hex"])
    if update_checksum:
        checksum = hashlib.md5(archive[table_off:extra_end]).digest()

    header = HEADER_STRUCT.pack(b"CSAF", version_flags, file_count, extra_size, checksum)
    archive[: HEADER_STRUCT.size] = header
    output_path.write_bytes(archive)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Repack CSAF archive from manifest.")
    parser.add_argument("manifest", help="manifest.json generated by csaf_unpack.py.")
    parser.add_argument("output", help="Output archive path.")
    parser.add_argument("--update-checksum", action="store_true", help="Recalculate header MD5.")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    output_path = Path(args.output)
    pack_archive(manifest_path, output_path, args.update_checksum)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
